759 - TypeError: base_launch_kernel() got an unexpected keyword argument 'ipython' IPython .13 has a breaking change, we need to check the IPython version and not pass a keyword arg.
wfastcgi - we should update the env vars on each request incase a previous request cleared them

TestUtilities - the version numbers aren't specified here, leading to a broken build in Dev10 if you have Dev11 installed.

Also includes rename from Python.VS.TestData -> TestData and addition of rolling run infrastructure